[tool.poetry]
name = "goit-ds-hw-02"
version = "0.1.0"
description = ""
authors = ["Liana Lotarets <lyanalotarets@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
faker = "^27.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
